name: ecsact
description: An Entity-Component-System framework for Dart.
version: 0.0.1
author: R.S. Schermer <roland0507@gmail.com>
homepage: https://github.com/RSSchermer/ECSact.dart
documentation:
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  observable: '^0.20.2'
  quiver: '^0.25.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
